extends:
  - recommended

apis:
  bookStore:
    root: v1/bookStore.yaml
  petStore:
    root: v1/petStore.yaml

theme:
  openapi:
    pathInMiddlePanel: true
    theme:
      rightPanel:
        backgroundColor: '#283046'
      sidebar:
        backgroundColor: '#283046'
        textColor: '#ffffff'
        activeTextColor: '#00a1b5'